name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: "recursive"

      - name: Install Dependencies
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          echo 'deb http://dk.archive.ubuntu.com/ubuntu/ bionic main' | sudo tee /etc/apt/sources.list.d/bionic-main.list
          echo 'deb http://dk.archive.ubuntu.com/ubuntu/ bionic universe' | sudo tee /etc/apt/sources.list.d/bionic-universe.list
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev qttools5-dev g++-5 gcc-5 build-essential cmake zlib1g-dev gcc-i686-linux-gnu g++-i686-linux-gnu openjdk-8-jdk -y

      - name: Build
        run: |
          export JAVA_HOME=$JAVA_HOME_8_X64
          mkdir build
          cd build
          export CFLAGS="-m32"
          export LDFLAGS="-m32"
          cmake \
           -DCMAKE_C_COMPILER=/usr/bin/gcc-5 \
           -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 \
           -DCMAKE_BUILD_TYPE=Release \
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json \
           -DCMAKE_INSTALL_PREFIX:PATH=/home/runner/UltimMC/UltimMC \
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ \
           -DLauncher_LAYOUT=lin-nodeps \
           -DLauncher_BUILD_PLATFORM=lin32 \
           -DLauncher_BUG_TRACKER_URL=https://github.com/UltimMC/Launcher/issues \
           -DLauncher_EMBED_SECRETS=On \
           $GITHUB_WORKSPACE

      - name: Compile
        run: |
          cd build
          make -j$(nproc)

      - name: Test
        run: |
          cd build
          make test
          cmake -E remove_directory "/home/runner/UltimMC/UltimMC"

      - name: Install
        run: |
          cd build
          make install
          chmod +x /home/runner/UltimMC/UltimMC/UltimMC
          chmod +x /home/runner/UltimMC/UltimMC/bin/UltimMC

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: mmc-cracked-lin64
          path: /home/runner/UltimMC
